// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djokbfmnvwiafhopgijr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqb2tiZm1udndpYWZob3BnaWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxODk4NDgsImV4cCI6MjA1Nzc2NTg0OH0.8ExUpbsjBjPmhSXpEiA51fNgWd63oLjumwwVJZQyreU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);